spring:
  datasource:
      url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driverClassName: com.mysql.jdbc.Driver
      hikari:
        connection-timeout: 60000
        maximum-pool-size: 5
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
        format-sql: true
      properties.hibernate.dialect: org.hibernate.dialect.MySQLInnoDBDialect
  thymeleaf:
      cache: false
      prefix: ${project.base-dir}/src/main/resources/templates/

#logging:
#  level:
#    ROOT: ERROR
#    org.springframework: ERROR
#    org.springframework.data: ERROR
#    org.springframework.web: ERROR
#    com.iphe: DEBUG
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file: /Logs/iphe.log
